<?php
/**
 * @file
 * Define main hooks for the module.
 */

/**
 * Implements hook_menu().
 */
function easyddb_hide_librarydropdown_menu() {
  $items = array();

  $items['admin/config/ding/admin-library'] = array(
    'title' => 'EasyDDB Hide Library dropdown',
    'description' => 'Admin page for library dropdown form display.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyddb_hide_librarydropdown_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'easyddb_hide_librarydropdown.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_panels_pane_content_alter().
 */
function easyddb_hide_librarydropdown_panels_pane_content_alter($content, $pane, $args, $contexts) {
  $load_form = variable_get('easyddb_hide_librarydropdown_list', '0');
  if ($pane->type == 'library_list' && $load_form) {
    $content->content = NULL;
  }
  return $content;
}
